### ISSUE TITLE
ClassCastException on rare occasion

### ISSUE THREAD

**Issue by andhie** [nicolasjafelle/Qachee#1]
Hi nicolas,

i'm faced with a weird issue that Qachee is returning wrong type on rare occasions

> FATAL EXCEPTION: main java.lang.ClassCastException: com.example.model.Product cannot be cast to com.example.model.Shop

the offending line is 

> shop = QacheeManager.getInstance().get(shop, Shop.class, false);

```
public void OnExploreCardClicked(View view, ExploreCardView.IExploreCard item) {
    if (item instanceof Product) {
        Product product = (Product) item;
        product = QacheeManager.getInstance().get(product, Product.class, false);

        FoodDetailsActivity.show(getActivity(), view, product.getKey());

    } else if (item instanceof Shop) {
        Shop shop = (Shop) item;
        shop = QacheeManager.getInstance().get(shop, Shop.class, false);

        MerchantDetailsActivity.show(getActivity(), view, shop.getKey());
    }
}
```

is there anyway i can debug this issue?

**Comment by nicolasjafelle** [comment]
Hi Andhie,

When you said rare occasions means what? is it not often at all??

You can download the library and attach as an Android Module in your project. It isn't difficult because it doesn't require any res folder, just plain java classes.

I don't have this issues at all, with the Product.class object do you suffer the same issue? Or just only with the Shop.class ??

Can you show us how are you inserting/adding the Shop.class and Product.class into Qachee? 

Thanks!

**Comment by andhie** [comment]
```
// Product.java 
public class Product extends QacheeableObject {

    @Expose
    private long ProductId;

    // other attr and methods ommited for brewity
    // hashCode() and equals() uses AS generated code based on ProductId only

    @Override
    public Long getKey() {
        return (ProductId ^ (ProductId >>> 32)); // same a hashCode()
    }
}
```

For Shop object its the same, I used ShopId instead.
This is how I add to the Qachee, same applies to Shop list

```
// this is a network operation done in background thread
List<Product> list = Product.asList(json);
QacheeManager.getInstance().addList(list);

// fire event with `list` to the UI thread and add into adapter
```

I think this issue is because of `getKey()` returns the same `Long` value. As I look into LruCache code, it uses `map.put(K, V)` which replaces the value of the same key. 
So it limits Qachee to only store a single class type, or 
to account more variables when generating a key. but that still wont solve the possible key collision

or is there a better way to solve this?

**Comment by nicolasjafelle** [comment]
The ProductId is a value generated by you in the app? or it is a value you receive from a json, typically a DB generated id?

The thing is... you have to find the way to use an attribute value that should be unique, not the same value in other object. 
You can also try something like this:

``` java
@Override 
public Long getKey() {
   return (someString + ProductId).hashCode(); 
} 
```

Maybe the sum/combination of ProductId with another value could be your solution.

One more thing: What happens if the key attribute in Qachee would be a String? That would be more helpfull for you? I am considering changed it in a new release.

**Comment by andhie** [comment]
The ProductId is server side DB generated value.

Currently i'm using sum of multiple `hashCode()` values to generate a key.
`hashCode()` produces an `int` result which limits `long` to values addressable by int. So probably using `String` as a key might be better as its not restricted to a finite value. Although it still doesn't really address the actual problem of multiple object type generated a same key.

Though i think a more safer approach would be creating individual cache for each object type.

**Comment by nicolasjafelle** [comment]
Wow!! I really like the individual cache for each object type. I will do a POC, you can fork Qachee and create some amazing stuff and then pull-request to my! 

To be honest, I have two projects ongoing right now so it will take me some time (free time) to do this.

**Comment by andhie** [comment]
I'm not too sure how to implement an individual cache efficiently. In my mind, i imagine the main container would be `HashMap<classTNameString, LruCache<Qacheeable>>`. But i'm not quite sure how multiple LruCache of 1/8 memory will behave. 

Lets say about 4MB (32/8) LruCache each on HDPI device. If you have 10 different class, and all cache are nearly full and total near 40MB, the individual LruCache still wont clear(?) cause it havent hit the limits. That would be pretty bad.

Or is there a better way that you could think of?

**Comment by nicolasjafelle** [comment]
Fixed with latest PR =D.
